### ISSUE TITLE
Running Hybritnet on Colab

### ISSUE THREAD

**Issue by KenR22** [JARVIS-MoCap/JARVIS-HybridNet#3]
Hi,

I have a machine without GPU and I was wondering if with the current version of Jarvis it would be possible to label videos locally and train the hybridnet on the colab?

Thanks

**Comment by timohueser** [comment]
Hi!

You can definitely label frames locally on any computer using the [AnnotationTool](https://jarvis-mocap.github.io/jarvis-docs/downloads/downloads/) and then export a trainingset to be used on a different machine with a GPU.

We currently don't have any colab demos you can use unfortunately, but I'll try my best to add some in the near future.

**Comment by KenR22** [comment]
That is great!

Thank you very much!
