### ISSUE TITLE
BBox Calculations Issue

### ISSUE THREAD

**Issue by anjaliipullabhotla** [JARVIS-MoCap/JARVIS-HybridNet#5]
Hi! I was wondering what bbox refers to in Lines 143-144 of https://github.com/JARVIS-MoCap/JARVIS-HybridNet/blob/master/jarvis/dataset/dataset2D.py
        center_y = (bboxs[0][1]+bboxs[0][3])/2
        center_x = (bboxs[0][0]+bboxs[0][2])/2
It looks like bbox is (x_min, y_min, x_range, y_range) from the Example_Dataset. Yet, center_x, center_y seems to be calculated using ({}_min + {}_range)/2 rather than {}_min + {}_range/2. Is this intentional, or is there something I am misunderstanding about the use of bbox in the dataset.

Thanks,
A

**Comment by timohueser** [comment]
Hi! Thanks for bringing this up! I think the way it is currently calculated is correct. The (x_min, y_min, x_range, y_range) format used in the dataset itself is converted to (x_min, y_min, x_max, y_max) format in the '_load_annotations' function (Line 131 in  [datasetBase.py](https://github.com/JARVIS-MoCap/JARVIS-HybridNet/blob/master/jarvis/dataset/datasetBase.py)).

Hope this clears things up :)
